# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "wholefin-tfstate-sand-844486820647"
    dynamodb_table = "wholefin-tfstate-lock"
    encrypt        = true
    key            = "live/sand/vpc/terraform.tfstate"
    region         = "us-east-2"
  }
}
