# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-2"

  assume_role {
    role_arn    = "arn:aws:iam::844486820647:role/Danny-TF"
    external_id = "52a15c10-bcf9-43f4-aa7b-dbb937267218"
  }
}

# CloudFront + WAFv2 (CLOUDFRONT scope) must live in us-east-1
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"

  assume_role {
    role_arn    = "arn:aws:iam::844486820647:role/Danny-TF"
    external_id = "52a15c10-bcf9-43f4-aa7b-dbb937267218"
  }
}
